server:
  port: 8282
  servlet:
    context-path: /resource-server-2

spring:
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        web.reactive: debug

