server:
  port: 8181
  servlet:
    context-path: /resource-server-1

spring:
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        security: debug
        web:
          reactive: debug
